sudo: false
language: python
python:
  - "3.4"

env:
  - TOXENV=py33 TEST_SUITE=clive
  - TOXENV=py34 TEST_SUITE=clive
  - TEST_SUITE=validate

install:
  - bin/travis/setup.sh $TEST_SUITE

script:
  - bin/travis/dispatch.sh $TEST_SUITE

notifications:
  email: false
  irc:
    channels: "irc.freenode.net#pyvideo"
    on_success: always
    on_failure: always
