description: |-
  In the continuous integration development process, automatic testing
  is critical. The application must be delivered properly to customers
  and users. And with frequent releases, manual testing is exhausting.

  Therefore developers need integration and system tests, aside from
  basic unit tests - to make sure their commits are integrated properly
  and did not break anything. No more: one hotfix creates two new bugs!

  For beginners: I will give a brief introduction to software testing
  and its types and talk about how easy is to start with writing
  automatic tests in Python.

  For advanced: I will present integration testing of Cleerio web
  mapping application (originally written in JavaScript and PHP) using
  Python together with Selenium project.
duration: 1966
recorded: '2017-10-28'
speakers:
- Magdalena Kabatova
thumbnail_url: https://i.ytimg.com/vi/3YekbncInhU/hqdefault.jpg
title: Testing of Web Applications Using Python
videos:
- type: youtube
  url: https://www.youtube.com/watch?v=3YekbncInhU
language: eng

